phantasma-io/phantasma-ng

Phantasma.Business/src/Blockchain/Contracts/MarketContract.cs
Phantasma.Business/src/Blockchain/Contracts/StakeContract.cs
Phantasma.Business/tests/Phantasma.Business.Tests.csproj
Phantasma.Core/src/Domain/Event.cs
Phantasma.Core/src/Domain/ICustomContract.cs
Phantasma.Core/src/Domain/INativeContract.cs
Phantasma.Core/src/Domain/SmartContract.cs
Phantasma.Core/src/Domain/VMObject.cs
Phantasma.Infrastructure/src/Phantasma.Infrastructure.csproj

[PHA-113] Fix MarketContractCriticalIssueIncorrectFeeCalculation
[PHA-114] Fix MarketContractHighIssueIncorrectFeeCalculation
[PHA-116] Fix MarketContractIncorrectFeesValidation
[PHA-117] Fix MarketContractIncorrectModifier
[PHA-118] Fix SmartContractUnusedState
[PHA-119] Fix StakeContractDateTimeDivideByZeroException
[PHA-120] Fix StakeContractDateTimeDoubleCast
[PHA-121] Fix StakeContractHardcodedValue
[PHA-122] Fix StakeContractHardcodedValueTokenSymbol
[PHA-124] Fix StakeContractMissedNotifyCallForStake
[PHA-125] Fix StakeContractMissleadingErrorMessage
[PHA-123] Fix StakeContractMissedNotifyCallForMasterClaim
[PHA-113]: https://phantasma.atlassian.net/browse/PHA-113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PHA-114]: …

. PHA-113 PHA-114 PHA-116 PHA-117 PHA-118 PHA-119 PHA-120 PHA-121 PHA-122 PHA-125 PHA-124 PHA-123

---

.gitignore
Phantasma.Business/src/Blockchain/Chain.cs
Phantasma.Business/src/Blockchain/CodeType.cs
Phantasma.Business/src/Blockchain/Contracts/AccountContract.cs
Phantasma.Business/src/Blockchain/Contracts/ConsensusContract.cs
Phantasma.Business/src/Blockchain/Contracts/GovernanceContract.cs
Phantasma.Business/src/Blockchain/Contracts/InteropContract.cs
Phantasma.Business/src/Blockchain/Contracts/ValidatorContract.cs
Phantasma.Business/src/Blockchain/ExtCalls.cs
Phantasma.Business/src/Blockchain/Nexus.cs
Phantasma.Business/src/Blockchain/Runtime.cs
Phantasma.Business/src/Phantasma.Business.csproj
Phantasma.Business/tests/Blockchain/Contracts/AccountContractTests.cs
Phantasma.Business/tests/Blockchain/InteropTests.cs
Phantasma.Business/tests/Blockchain/RuntimeTests.cs
Phantasma.Core/src/Cryptography/Address.cs
Phantasma.Core/src/Domain/DomainSettings.cs
Phantasma.Core/src/Domain/IChain.cs
Phantasma.Core/src/Domain/INexus.cs
Phantasma.Core/src/Domain/IRuntime.cs
Phantasma.Infrastructure/src/Phantasma.Infrastructure.csproj
Phantasma.Node/ABCIConnector.cs
Phantasma.Node/Interop/TokenSwapper.cs
Phantasma.Node/Node.cs
Phantasma.Node/ResponseHelper.cs

Removed Phantasma.Business dependency from Tendermint.
Initial validators now can be 1 except in mainnet nexus.

Removed Phantasma.Business dependency from Tendermint

---

Phantasma.Business/src/Blockchain/Nexus.cs
Phantasma.Business/src/VM/Utils/DisasmUtils.cs

Extcalls: Fix for Nexus.CreateToken

---

Phantasma.Business/src/Blockchain/ExtCalls.cs
Phantasma.Business/src/Blockchain/Nexus.cs
Phantasma.Business/src/Blockchain/Runtime.cs
Phantasma.Business/src/Blockchain/Tokens/TokenUtils.cs
Phantasma.Core/src/Domain/INexus.cs

More fixes for nexus

---

Phantasma.Business/src/Blockchain/Contracts/StakeContract.cs
Phantasma.Business/src/Blockchain/Nexus.cs

Initial validator set now auto-stakes.

Initial validator set now auto-stakes  0e8fa3

---

Phantasma.Business/src/Blockchain/Chain.cs
Phantasma.Business/src/Blockchain/GasExtensions.cs
Phantasma.Business/src/VM/Utils/DisasmUtils.cs

ExtractGasDetails now supports custom contracts

ExtractGasDetails now supports custom contracts

---

Phantasma.Business/src/Blockchain/Chain.cs

ExtractGas now compatible with upgradeable contracts

ExtractGas now compatible with upgradeable contracts

---

Phantasma.Business/src/VM/Utils/DisasmUtils.cs

Fix for Runtime.UpgradeContract

---

Phantasma.Business/src/Blockchain/Nexus.cs

NEP5 legacy swap supply added in migration

NEP5 legacy swap supply added in migration

---

Phantasma.Business/src/Blockchain/Nexus.cs
Phantasma.Business/src/Blockchain/Oracle.cs
Phantasma.Business/src/Blockchain/Runtime.cs
Phantasma.Core/src/Domain/IOracleReader.cs
Phantasma.Tests/ChainTests.cs
Phantasma.Tests/Phantasma.Simulator/NexusSimulator.cs

Oracles changes and more legacy test fixes

---

Phantasma.Tests/Phantasma.Simulator/NexusSimulator.cs

Added LastBlockWasSuccessful()

---

Phantasma.Business/src/Blockchain/Nexus.cs
Phantasma.Core/src/Domain/Transaction.cs
Phantasma.Tests/ContractTests/ConsensusContractTest.cs
Phantasma.Tests/Phantasma.Simulator/NexusSimulator.cs

Fix for validator keys in test simulator

---

Phantasma.Business/src/Blockchain/Contracts/SwapContract.cs
Phantasma.Business/src/Blockchain/Nexus.cs
Phantasma.Tests/ContractTests/ExchangeContractTests.cs
Phantasma.Tests/ContractTests/StakeContractTest.cs
Phantasma.Tests/ContractTests/SwapContractTest.cs
Phantasma.Tests/Exploits/Exploits.cs
Phantasma.Tests/Exploits/WhenSystemAddressUsedAsSourceInScript.cs
Phantasma.Tests/Phantasma.Simulator/NexusSimulator.cs

Tests - Swap & Exchange + Swap fixed

---

Phantasma.Tests/ChainTests.cs
Phantasma.Tests/ContractTests/ExchangeContractTests.cs
Phantasma.Tests/ContractTests/StakeContractTest.cs
Phantasma.Tests/ContractTests/SwapContractTest.cs
Phantasma.Tests/Exploits/Exploits.cs
Phantasma.Tests/OldContractTests.cs
Phantasma.Tests/Phantasma.Simulator/NexusSimulator.cs

Added a lot of tests to the exchange parte.
Thank you.

Exchange tests added.

---

DOCKER/Dockerfile
build-docker-macos-arm64.sh
build-docker-testnet-arm64.sh
build-docker-testnet-windows.sh
build-docker-testnet.sh
build-docker-windows.sh
build-docker.sh
publish-docker-arm64.sh
publish-docker.sh
testnet-startup.sh

Just updated the docker scripts to allow to run on linux

Update Docker scripts

---

Phantasma.Business/src/Blockchain/Contracts/ExchangeContract.cs
Phantasma.Business/src/Blockchain/TransactionExtensions.cs
Phantasma.Tests/ChainTests.cs
Phantasma.Tests/ContractTests/ExchangeContractTests.cs
Phantasma.Tests/ContractTests/MarketContractTest.cs
Phantasma.Tests/ContractTests/StakeContractTest.cs
Phantasma.Tests/ContractTests/SwapContractTest.cs
Phantasma.Tests/Phantasma.Simulator/NexusSimulator.cs
Phantasma.Tests/TokenTests.cs

[Added] Whitelist Claim
[Update] Updated all the Exchange contract tests to pass.
[Update] Updated all the Market contract tests to pass. (Less 1)
[Update] Updated all the Stake contract tests to pass.
[Update] Updated all the Swap contract tests to pass.

Fix a lot of Tests and Updated the Whitelist.

---

Phantasma.Business/src/Blockchain/GasMachine.cs
Phantasma.Business/src/Blockchain/Oracle.cs
Phantasma.Business/src/Blockchain/Runtime.cs
Phantasma.Core/src/Domain/IOracleReader.cs

Protection for oracle call spam

---

Phantasma.Business/src/Blockchain/Chain.cs
Phantasma.Core/src/Domain/Block.cs
Phantasma.Node/Oracles/SpookOracle.cs
Phantasma.Tests/ChainTests.cs
Phantasma.Tests/ContractTests/ConsensusContractTest.cs
Phantasma.Tests/ContractTests/ExchangeContractTests.cs
Phantasma.Tests/ContractTests/MarketContractTest.cs
Phantasma.Tests/NFTTests.cs
Phantasma.Tests/OracleTests.cs
Phantasma.Tests/Phantasma.Tests.csproj

New tests & fix's 

---

Phantasma.Business/src/Blockchain/Chain.cs
Phantasma.Business/src/Blockchain/GasMachine.cs
Phantasma.Business/src/Blockchain/Oracle.cs
Phantasma.Node/ABCIConnector.cs
Phantasma.Tests/OracleTests.cs
Phantasma.Tests/TokenTests.cs

Fixed oracle tests and token tests

---

Phantasma.Business/src/Blockchain/Contracts/ExchangeContract.cs
Phantasma.Business/src/Blockchain/Contracts/LPContract.tomb
Phantasma.Business/src/Blockchain/Contracts/SwapContract.cs
Phantasma.Business/src/Blockchain/Runtime.cs
Phantasma.Business/src/VM/Utils/DisasmUtils.cs
Phantasma.Core/src/Domain/DomainSettings.cs
Phantasma.Tests/AssemblerTests.cs
Phantasma.Tests/ChainTests.cs
Phantasma.Tests/ContractTests/AccountContracTest.cs
Phantasma.Tests/ContractTests/ExchangeContractTests.cs
Phantasma.Tests/ContractTests/FriendContractTest.cs
Phantasma.Tests/ContractTests/MarketContractTest.cs
Phantasma.Tests/ContractTests/SaleContractTest.cs
Phantasma.Tests/ContractTests/StakeContractTest.cs
Phantasma.Tests/ContractTests/SwapContractTest.cs
Phantasma.Tests/Exploits/Exploits.cs
Phantasma.Tests/Exploits/WhenSystemAddressUsedAsSourceInScript.cs
Phantasma.Tests/NFTTests.cs
Phantasma.Tests/Phantasma.Simulator/NexusSimulator.cs
Phantasma.Tests/Phantasma.Simulator/OracleSimulator.cs

Virtual Pools

---

Phantasma.Tests/OracleTests.cs
Phantasma.Tests/Phantasma.Tests.csproj

Update Oracle Test

---

Phantasma.Business/tests/Blockchain/OracleTests.cs
Phantasma.Business/tests/Phantasma.Business.Tests.csproj

Update Oracle tests

---

Phantasma.Business/tests/Blockchain/Exploits/Exploits.cs
Phantasma.Business/tests/Blockchain/Exploits/WhenSystemAddressUsedAsSourceInScript.cs
Phantasma.Tests/AssemblerTests.cs
Phantasma.Tests/ChainTests.cs
Phantasma.Tests/ContractTests/AccountContracTest.cs
Phantasma.Tests/ContractTests/ConsensusContractTest.cs
Phantasma.Tests/ContractTests/ExchangeContractTests.cs
Phantasma.Tests/ContractTests/FriendContractTest.cs
Phantasma.Tests/ContractTests/MarketContractTest.cs
Phantasma.Tests/ContractTests/SaleContractTest.cs
Phantasma.Tests/ContractTests/StakeContractTest.cs
Phantasma.Tests/ContractTests/SwapContractTest.cs
Phantasma.Tests/CryptoTests.cs
Phantasma.Tests/HashTests.cs
Phantasma.Tests/MathTests.cs
Phantasma.Tests/MerkleTreeTests.cs
Phantasma.Tests/NFTTests.cs
Phantasma.Tests/OldContractTests.cs
Phantasma.Tests/OracleTests.cs
Phantasma.Tests/PayTests.cs
Phantasma.Tests/SerializationTests.cs
Phantasma.Tests/StorageTests.cs
Phantasma.Tests/TokenTests.cs
Phantasma.Tests/VMTests.cs
Phantasma.Tests/WalletTests.cs

Namespace changes & tests to the correct directory (Some)

---

.github/workflows/dotnet.yml

Update dotnet.yml (remove Phatasma.Tests)

---

DOCKER/wrapper.sh
Phantasma.Business/src/Phantasma.Business.csproj
Phantasma.Core/src/Phantasma.Core.csproj
Phantasma.Tendermint.RPC/Phantasma.Tendermint.RPC.csproj
Phantasma.Tendermint/Phantasma.Tendermint.csproj
build-docker-arm64.sh
build-docker-testnet-arm64.sh
build-docker-testnet.sh
build-docker.sh
publish-docker-arm64.sh
publish-docker.sh

Fixing configurations, runners and builders

---

Phantasma.Business/tests/Blockchain/Storage/ArchiveExtensionsTests.cs
Phantasma.Business/tests/Blockchain/Storage/ArchiveTests.cs
Phantasma.Business/tests/Blockchain/Storage/PrivateArchiveEncryptionTests.cs
Phantasma.Business/tests/Blockchain/Storage/SharedArchiveEncryptionTests.cs
Phantasma.Core/tests/Storage/KeyStoreTests.cs
Phantasma.Core/tests/Storage/StorageTests.cs

More Tests

---

Phantasma.Business/src/Blockchain/Chain.cs
Phantasma.Business/src/Blockchain/Contracts/InteropContract.cs
Phantasma.Business/src/Blockchain/Filter.cs
Phantasma.Business/src/Blockchain/Nexus.cs
Phantasma.Business/tests/Blockchain/ChainTests.cs
Phantasma.Business/tests/Blockchain/FilterTests.cs
Phantasma.Business/tests/Blockchain/Tokens/TokenTests.cs
Phantasma.Business/tests/Simulator/NexusSimulator.cs
Phantasma.Business/tests/Simulator/OracleSimulator.cs
Phantasma.Core/src/Storage/Context/StorageList.cs

Added filter tests

---

Phantasma.Business/src/Blockchain/Filter.cs
Phantasma.Business/tests/Blockchain/ChainTests.cs
Phantasma.Business/tests/Simulator/OracleSimulator.cs

Fix for filter tests

---

DOCKER/testnet/node0/config_testnet_node0.json
DOCKER/testnet/node1/config_testnet_node1.json
DOCKER/testnet/node2/config_testnet_node2.json
DOCKER/testnet/node3/config_testnet_node3.json
Phantasma.Business/src/Blockchain/Webhook.cs
Phantasma.Node/Settings.cs

Fix configs

---

Phantasma.Business/src/Blockchain/Filter.cs
Phantasma.Business/tests/Blockchain/ChainTests.cs
Phantasma.Business/tests/Blockchain/Contracts/Legacy/ExchangeContractTests.cs
Phantasma.Business/tests/Blockchain/Contracts/Legacy/StakeContractTestLegacy.cs
Phantasma.Business/tests/Blockchain/OracleTests.cs

Fix for oracle tests

---

Phantasma.Business/src/Blockchain/ExtCalls.cs
Phantasma.Business/src/Blockchain/Runtime.cs
Phantasma.Business/src/VM/Utils/DisasmUtils.cs
Phantasma.Core/src/Cryptography/Address.cs

Refactor of extcalls registration

---

Phantasma.Business/src/Blockchain/Nexus.cs

Fix for NFT burn with infusions

---

Phantasma.Business/src/Blockchain/Nexus.cs
Phantasma.Business/tests/Blockchain/Contracts/Legacy/StakeContractTestLegacy.cs
Phantasma.Business/tests/Blockchain/Exploits/Exploits.cs

Added fix to MasterClaim & Tests

---

Phantasma.Business/src/Blockchain/Nexus.cs

Added check for token contract upgrade

---

Phantasma.Business/tests/Blockchain/Exploits/Exploits.cs

Increasing test coverage

---

Phantasma.Business/src/Blockchain/Chain.cs
Phantasma.Business/src/Blockchain/ChainExecutionContext.cs
Phantasma.Business/src/Blockchain/Contracts/AccountContract.cs
Phantasma.Business/src/Blockchain/Contracts/GovernanceContract.cs
Phantasma.Business/src/Blockchain/Contracts/StakeContract.cs
Phantasma.Business/src/Blockchain/Contracts/StorageContract.cs
Phantasma.Business/src/Blockchain/Contracts/ValidatorContract.cs
Phantasma.Business/src/Blockchain/ExtCalls.cs
Phantasma.Business/src/Blockchain/Nexus.cs
Phantasma.Business/tests/Blockchain/Exploits/Exploits.cs
Phantasma.Core/src/Domain/INexus.cs

More validations added

---

Phantasma.Infrastructure/src/API/Controllers/TransactionController.cs

Fixed error handling in GetTransaction

---

Phantasma.Business/src/Blockchain/Filter.cs
Phantasma.Business/tests/Blockchain/FilterTests.cs
Phantasma.Business/tests/Simulator/NexusSimulator.cs
Phantasma.Business/tests/Simulator/OracleSimulator.cs
Phantasma.Infrastructure/src/API/Controllers/TransactionController.cs

Added quota sum filter

---

Phantasma.Infrastructure/src/API/Controllers/TransactionController.cs
Phantasma.Infrastructure/src/API/NexusAPI.cs
Phantasma.Node/ABCIConnector.cs
Phantasma.Node/Node.cs
Phantasma.Node/Settings.cs

Support for Tendermint key override via args

---

Phantasma.Business/src/Blockchain/Nexus.cs

Update Nexus.cs - for mainnet

---

Phantasma.Business/tests/Blockchain/RuntimeTestsSimulator.cs
Phantasma.Business/tests/CodeGen/Assembler/InstructionTests.cs
Phantasma.Business/tests/VM/DisassemblerTest.cs
Phantasma.Core/tests/ExtensionMethodsTests.cs

More tests to increase just a bit the test coverage.

---

Phantasma.Business/src/Blockchain/ExtCalls.cs
Phantasma.Infrastructure/src/API/Controllers/RpcController.cs

Remove validation for gets

---

Phantasma.Business/src/Blockchain/Nexus.cs
Phantasma.Business/tests/Simulator/NexusSimulator.cs
Phantasma.Business/tests/VM/DisassemblerTest.cs

Custom protocol version support in tests  0f91a6

---

Phantasma.Business/tests/xunit.runner.json

Fix to the runner

---

Phantasma.Business/src/Blockchain/Nexus.cs
Phantasma.Business/tests/Blockchain/Exploits/Exploits.cs

Change to the nexus to fix a issue.

---

Phantasma.Business/src/Blockchain/Contracts/ConsensusContract.cs
Phantasma.Business/src/Blockchain/Contracts/StakeContract.cs
Phantasma.Business/src/Blockchain/Nexus.cs
Phantasma.Business/tests/Blockchain/Contracts/ConcensusContractTests.cs
Phantasma.Core/src/Domain/Transaction.cs

- Update to the consesus contract
- Update to the stake contract
- Update to Nexus
- Update to Transaction

Consensus Multi Sig, Stake, Validations

---

Phantasma.Business/src/Blockchain/Contracts/ConsensusContract.cs
Phantasma.Business/tests/Blockchain/Contracts/ConcensusContractTests.cs
Phantasma.Business/tests/Simulator/NexusSimulator.cs

The test needs to be fixed, the transction retrived from the blockchain is not being decoded in a proper way.
Thank you.

Almost there, but needs some more testing.

---

Phantasma.Business/src/Blockchain/Contracts/StakeContract.cs
Phantasma.Business/src/Blockchain/ExtCalls.cs
Phantasma.Business/src/Blockchain/Nexus.cs
Phantasma.Business/src/Blockchain/Runtime.cs
Phantasma.Business/tests/Blockchain/BlockOracleReaderTests.cs
Phantasma.Business/tests/Blockchain/CodeTypeTests.cs
Phantasma.Business/tests/Blockchain/Contracts/ConcensusContractTests.cs
Phantasma.Business/tests/Blockchain/Contracts/Legacy/ExchangeContractTests.cs
Phantasma.Business/tests/Blockchain/Contracts/MailContractTests.cs
Phantasma.Business/tests/Blockchain/CustomContractTests.cs
Phantasma.Business/tests/Blockchain/NexusTestsSimulator.cs
Phantasma.Business/tests/Blockchain/TransactionExtensionsTests.cs
Phantasma.Business/tests/Blockchain/VMExtensionsTests.cs
Phantasma.Business/tests/Simulator/NexusSimulator.cs
Phantasma.Core/src/Domain/Validation.cs
Phantasma.Core/tests/Cryptography/AddressTests.cs
Phantasma.Core/tests/Cryptography/ECDsa/ECDsaSignature.cs
Phantasma.Core/tests/Domain/BlockTests.cs
Phantasma.Core/tests/Domain/DomainExtensionsTests.cs
Phantasma.Core/tests/Domain/TransactionTests.cs
Phantasma.Core/tests/ThrowTests.cs

Update to some known issues

---

Phantasma.Business/src/Blockchain/Nexus.cs
Phantasma.Business/tests/Blockchain/NexusTestsSimulator.cs
Phantasma.Business/tests/Simulator/NexusSimulator.cs

Fix NexusSimulator & NexusTestsSimulator
Fixing the allowed amount for the transaction
Thank you.

Fix to the Organization movements  & nexus simulator.

---

Phantasma.Business/src/Blockchain/NativeContract.cs
Phantasma.Core/src/Types/Timestamp.cs

Allow more types to be converted.

---

Phantasma.Business/src/Blockchain/Contracts/ConsensusContract.cs
Phantasma.Core/src/Domain/VMObject.cs
Phantasma.Infrastructure/src/API/Controllers/BlockController.cs
Phantasma.Infrastructure/src/API/Controllers/ContractController.cs
Phantasma.Infrastructure/src/API/Controllers/PlatformController.cs
Phantasma.Infrastructure/src/API/Controllers/TransactionController.cs
Phantasma.Infrastructure/src/API/Controllers/ValidatorController.cs
Phantasma.Infrastructure/src/API/Structs.cs

InvokeRawScript
Improve overall API
Update VMObject to add the size on the Unserialized

Merge into dev changes need

---

Phantasma.Business/src/Blockchain/Contracts/ConsensusContract.cs
Phantasma.Core/src/Utils/IOUtils.cs

Added serialazables to Consensus
Thank you.

Added WriteTimestamp and ReadTimestamp

---

.github/workflows/dotnet.yml
Phantasma.Node/ABCIConnector.cs

Merge to dev, fix's to the consensus 

---

Phantasma.Business/src/Blockchain/ExtCalls.cs
Phantasma.Business/src/Blockchain/Runtime.cs
Phantasma.Business/tests/Blockchain/InteropTests.cs
Phantasma.Core/src/Domain/IRuntime.cs

PHA-1002: Removed dapp random generator out of chain codebase

---

Phantasma.Node/Node.cs

Fix Node for deployment

---

Phantasma.Business/src/Blockchain/Chain.cs
Phantasma.Business/src/Blockchain/Contracts/ConsensusContract.cs
Phantasma.Business/src/Blockchain/Contracts/ValidatorContract.cs
Phantasma.Business/src/Blockchain/Nexus.cs
Phantasma.Business/tests/Blockchain/Contracts/ValidatorContractTests.cs
Phantasma.Business/tests/Blockchain/NexusTestsSimulator.cs
Phantasma.Business/tests/Blockchain/RuntimeTestsSimulator.cs

Change to the nexus - Change the order of the if
Change the chain - Is just a space
Change the Validator Contract - it's a fix ( it had an issue where is was only retriving 1 ). Change the consensus Contract to query the total validators and not only the primary ones.
Thank you.

Fix to the validator contract.

---

.github/workflows/dotnet.yml
Phantasma.Business/src/Blockchain/Contracts/GovernanceContract.cs
Phantasma.Business/src/Blockchain/Contracts/StakeContract.cs
Phantasma.Business/src/Blockchain/Contracts/ValidatorContract.cs
Phantasma.Business/src/Blockchain/ExtCalls.cs
Phantasma.Business/src/Blockchain/Filter.cs
Phantasma.Business/src/Blockchain/Nexus.cs
Phantasma.Business/src/Blockchain/Organization.cs
Phantasma.Business/src/Blockchain/Runtime.cs
Phantasma.Business/tests/Blockchain/Contracts/Legacy/StakeContractTestLegacy.cs
Phantasma.Business/tests/Blockchain/Contracts/ValidatorContractTests.cs
Phantasma.Business/tests/Blockchain/Exploits/Exploits.cs
Phantasma.Business/tests/Blockchain/FilterTests.cs
Phantasma.Core/src/Domain/DomainSettings.cs
Phantasma.Core/src/Storage/Context/KeyStoreStorage.cs
Phantasma.Core/src/Storage/Context/MemoryStorage.cs
Phantasma.Core/src/Storage/Context/StorageChangeSet.cs
Phantasma.Core/src/Storage/Context/StorageContext.cs
Phantasma.Infrastructure/src/API/Controllers/AccountController.cs
Phantasma.Infrastructure/src/API/Controllers/OrganizationController.cs

[Update] Organization Controller -> Validate null string.
[Added] AccountController -> GetAllTheAddressesBySymbol
[Updated] Filter.cs
[Update] StorageContext -> Added a Count function.
[Update] GovernanceContract to allow to send system. to set the values.
[Update] ValidatorContract back to what it was.
[Update] Nexus -> Remove constant warnings for the infusion address. (only if it's above the quota)
[Added] ValidatorContract Tests

Big Update

---

Phantasma.Business/src/Blockchain/Contracts/GasContract.cs
Phantasma.Business/src/Blockchain/NativeContract.cs
Phantasma.Node/Oracles/CoinGecko.cs
Phantasma.Node/Oracles/CryptoCompare.cs
Phantasma.Node/Oracles/Pricer.cs
Phantasma.Node/Oracles/SpookOracle.cs

Update GasContract.cs - Fix inflation

---

Phantasma.Business/src/Blockchain/Contracts/GasContract.cs
Phantasma.Business/src/Blockchain/Contracts/StakeContract.cs
Phantasma.Business/src/Blockchain/NativeContract.cs
Phantasma.Business/src/Blockchain/Nexus.cs
Phantasma.Business/tests/Blockchain/ChainTests.cs
Phantasma.Business/tests/Blockchain/Contracts/Legacy/ExchangeContractTests.cs
Phantasma.Business/tests/Blockchain/Contracts/Legacy/StakeContractTestLegacy.cs
Phantasma.Business/tests/Blockchain/Exploits/Exploits.cs
Phantasma.Business/tests/Simulator/NexusSimulator.cs
Phantasma.Core/src/Domain/DomainSettings.cs
Phantasma.Node/Node.cs

Remove Node Filters
Fix nfts and inflation
Thank you.

Fix inflation and NFT's

---

Phantasma.Business/tests/Blockchain/Exploits/Exploits.cs

Update tests 

---

Phantasma.Business/src/Blockchain/Chain.cs
Phantasma.Business/src/Blockchain/Nexus.cs

Fix the Auto Inflation

---

Phantasma.Business/src/Blockchain/Chain.cs
Phantasma.Business/src/Blockchain/Contracts/AccountContract.cs
Phantasma.Business/src/Blockchain/Contracts/StorageContract.cs
Phantasma.Business/src/Blockchain/ExtCalls.cs
Phantasma.Business/src/Blockchain/GasMachine.cs
Phantasma.Business/src/Blockchain/Nexus.cs
Phantasma.Business/src/Blockchain/NexusExtensions.cs
Phantasma.Business/src/Blockchain/RuntimeWriteExtensions.cs
Phantasma.Business/tests/Blockchain/ChainTests.cs
Phantasma.Business/tests/Blockchain/Contracts/ConcensusContractTests.cs
Phantasma.Business/tests/Blockchain/Contracts/Legacy/AccountContracTestLegacy.cs
Phantasma.Business/tests/Blockchain/Contracts/Legacy/MarketContractTestLegacy.cs
Phantasma.Business/tests/Blockchain/Contracts/Legacy/StakeContractTestLegacy.cs
Phantasma.Business/tests/Blockchain/Contracts/SwapContractTest.cs
Phantasma.Business/tests/Blockchain/NFTTests.cs
Phantasma.Business/tests/Blockchain/NexusTests.cs
Phantasma.Business/tests/Blockchain/Storage/FileStorageTests.cs
Phantasma.Business/tests/Blockchain/Tokens/TokenTests.cs
Phantasma.Business/tests/Simulator/NexusSimulator.cs
Phantasma.Core/src/Domain/DomainSettings.cs
Phantasma.Core/tests/Cryptography/SignatureTests.cs
Phantasma.Core/tests/Utils/RequestTests.cs

Fix's and Improvements  

---

Phantasma.Business/src/Blockchain/Storage/SmartContractSheet.cs

Update SmartContractSheet.cs fix namings

---

Phantasma.Business/src/Blockchain/Chain.cs
Phantasma.Business/src/Blockchain/Storage/SmartContractSheet.cs

Fix to the Chain blockTimestamp & Encoding proper names.

---

Phantasma.Business/src/Blockchain/Chain.cs
Phantasma.Business/src/Blockchain/ChainExtensions.cs
Phantasma.Business/src/Blockchain/Nexus.cs
Phantasma.Business/src/Blockchain/Organization.cs
Phantasma.Business/src/Blockchain/Runtime.cs
Phantasma.Business/src/Blockchain/SerializedBlockList.cs
Phantasma.Business/src/Blockchain/Storage/SmartContractSheet.cs
Phantasma.Business/src/Blockchain/TransactionExtensions.cs
Phantasma.Business/tests/Blockchain/ChainTests.cs
Phantasma.Business/tests/Blockchain/Contracts/Legacy/StakeContractTestLegacy.cs
Phantasma.Business/tests/Blockchain/SerializedBlockListTests.cs
Phantasma.Business/tests/Blockchain/Storage/FileStorageTests.cs
Phantasma.Business/tests/Simulator/NexusSimulator.cs
Phantasma.Core/src/Domain/IChain.cs
Phantasma.Core/src/Domain/INexus.cs
Phantasma.Core/src/Domain/IOrganization.cs
Phantasma.Core/src/Domain/IRuntime.cs
Phantasma.Core/src/Domain/Transaction.cs
Phantasma.Infrastructure/src/API/Controllers/TransactionController.cs
Phantasma.Infrastructure/src/API/NexusAPI.cs
Phantasma.Node/ABCIConnector.cs

Fix references & remove references to TxV2

---

Phantasma.Core/tests/Utils/RequestTests.cs

Fix the tests for requests.

---

Phantasma.Business/src/Blockchain/Contracts/ExchangeContract.cs
Phantasma.Business/src/Blockchain/Contracts/LPContract.tomb
Phantasma.Business/src/Blockchain/ExtCalls.cs
Phantasma.Business/src/Blockchain/Runtime.cs

Add costs to DAO's and Fix Burn Crowns

---

Phantasma.Business/src/Blockchain/Chain.cs
Phantasma.Business/src/Blockchain/Contracts/ExchangeContract.cs
Phantasma.Business/src/Blockchain/Contracts/SwapContract.cs

Update Chain to fix cosmic swaps.
Fix the naming of GetDexVersion
Thank you.

Fix to cosmic swaps

---

Phantasma.Business/src/Blockchain/Chain.cs
Phantasma.Business/src/VM/Disassembler.cs
Phantasma.Business/src/VM/Utils/DisasmUtils.cs
Phantasma.Business/tests/VM/DisassemblerTest.cs

Detection of jumps in transaction scripts

---

CHANGELOG.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
Phantasma.Business/src/Blockchain/Chain.cs
Phantasma.Business/src/Blockchain/Contracts/Native/ConsensusContract.cs
Phantasma.Business/src/Blockchain/Contracts/Native/ExchangeContract.cs
Phantasma.Business/src/Blockchain/Contracts/Native/ValidatorContract.cs
Phantasma.Business/src/Blockchain/Nexus.cs
Phantasma.Business/src/Blockchain/NexusExtensions.cs
Phantasma.Business/src/Blockchain/Tokens/TokenUtils.cs
Phantasma.Business/src/Blockchain/VM/ExtCalls.cs
Phantasma.Business/src/Phantasma.Business.csproj
Phantasma.Business/src/VM/ScriptContext.cs
Phantasma.Business/tests/Blockchain/BlockOracleReaderTests.cs
Phantasma.Business/tests/Blockchain/Contracts/ConcensusContractTests.cs
Phantasma.Business/tests/Blockchain/NexusTestsSimulator.cs
Phantasma.Business/tests/Simulator/NexusSimulator.cs
Phantasma.Core/src/Cryptography/Address.cs
Phantasma.Core/src/Domain/IChain.cs
Phantasma.Core/src/Domain/INexus.cs
Phantasma.Node/ABCIConnector.cs
Phantasma.Node/Oracles/SpookOracle.cs

Fix's and improvements 

---

Phantasma.Business/src/Blockchain/Chain.cs
Phantasma.Business/src/Blockchain/Contracts/Native/ConsensusContract.cs
Phantasma.Business/src/Blockchain/Contracts/Native/ExchangeContract.cs
Phantasma.Business/src/Blockchain/Contracts/Native/InteropContract.cs
Phantasma.Business/src/Blockchain/Contracts/Native/ValidatorContract.cs
Phantasma.Business/src/Blockchain/Nexus.cs
Phantasma.Business/src/Blockchain/NexusExtensions.cs
Phantasma.Business/src/Blockchain/Webhook.cs
Phantasma.Business/tests/Blockchain/Contracts/Legacy/ExchangeContractTests.cs
Phantasma.Business/tests/CodeGen/Assembler/SemantemeTests.cs
Phantasma.Core/src/Storage/Context/StorageChangeSet.cs
Phantasma.Core/src/Storage/Context/StorageKey.cs
Phantasma.Node/ABCIConnector.cs

[Update] Consensus Contract to allow to get Addresses and Transaction easier.
[Update] Exchange Contract Improved validation to existing methods. (Still needs to be updated the RemoveLiquidity

Tests, Comments and Exchange Contract Improvements.

---

.gitignore
Phantasma.Business/src/Blockchain/Webhook.cs
Phantasma.Infrastructure/src/API/NexusAPI.cs
Phantasma.Node/ABCIConnector.cs

Fix Transaction issue

---

Phantasma.Infrastructure/src/API/NexusAPI.cs

Fix Instead of hash to string

---

Phantasma.Infrastructure/src/API/NexusAPI.cs

Dev fix data storage

---

Phantasma.Infrastructure/src/API/NexusAPI.cs

Merge into Dev.

---

Phantasma.Business/src/Phantasma.Business.csproj
Phantasma.Core/src/Domain/VMObject.cs
Phantasma.Core/src/Phantasma.Core.csproj
Phantasma.Tendermint.RPC/Phantasma.Tendermint.RPC.csproj
Phantasma.Tendermint/Phantasma.Tendermint.csproj

Added missing type casts in VM + Nuget updates

---

Phantasma.Business/src/Blockchain/VM/ExtCalls.cs
Phantasma.Business/tests/Blockchain/InteropTests.cs

Extcalls: Added GetTokenSupply and GetAvailableTokenSymbols

---

Phantasma.Business/src/Blockchain/VM/ExtCalls.cs
Phantasma.Business/tests/Simulator/NexusSimulator.cs

Extcalls: Added Runtime.GetAvailableNFTSymbols

---

Phantasma.Business/src/Blockchain/VM/ExtCalls.cs

Extcalls: Added Runtime.ContractExists

---

.github/workflows/dotnet-publish.yml

Fix duplicates

---

.github/workflows/comment-on-pr.yml
.github/workflows/dotnet-publish.yml
.github/workflows/dotnet.yml
Phantasma.Business/src/Blockchain/Contracts/Native/GasContract.cs
Phantasma.Core/src/Phantasma.Core.csproj
README.md

Fix to current version.

---

Phantasma.Business/tests/Blockchain/Contracts/Legacy/StakeContractTestLegacy.cs

Fix the stake test was not working

---

DOCKER/Dockerfile
DOCKER/DockerfileTestnet
DOCKER/wrapper.sh
Phantasma.Business/src/Blockchain/Contracts/Native/ExchangeContract.cs
Phantasma.Business/tests/Blockchain/Contracts/Legacy/ExchangeContractTests.cs
build-docker-amd64.sh
publish-docker-amd64.sh
publish-docker-arm64.sh

Creating pool / Swap and Add Liquidity
Thank you.

Fixing some docker dependencies & fixing the Exchange issues.

---

Phantasma.Business/src/Blockchain/Chain.cs
Phantasma.Infrastructure/src/API/Controllers/TransactionController.cs

Update to the SendRawTransaction Output

---

.github/workflows/docker-image.yml
Phantasma.Business/src/Blockchain/Contracts/Native/ExchangeContract.cs
Phantasma.Business/tests/Blockchain/Contracts/Legacy/ExchangeContractTests.cs

Fix some smaller issue's on the Dex

---

Phantasma.Business/src/Blockchain/NexusTokens.cs

Fixing small issues.

---

Phantasma.Infrastructure/src/API/Controllers/BlockController.cs

Fixing the GetBlockByHeight == 0

Update BlockController, API Issue

---

Phantasma.Business/src/Blockchain/Contracts/Native/ConsensusContract.cs
Phantasma.Business/tests/Blockchain/Contracts/ConcensusContractTests.cs
Phantasma.Core/src/Domain/Contract/Consensus/Structs/PollPresenceVotes.cs
Phantasma.Core/src/Domain/Contract/Consensus/Structs/PollVotesValue.cs

[Fix] Fixed the way the consensus works with the polls. 
[Added] More tests to check some special cases.

Issue 49 - Multivoting on the same poll.

---

CHANGELOG.md
DOCKER/DockerfileTestnet
DOCKER/DockerfileTestnetDebug
Phantasma.Node/src/ABCIConnector.cs

- Fix DockerFiles
- Fix ABCI Connector issue if the block was null .

Fix's to the docker files and the ABCI.

---

CHANGELOG.md
Phantasma.Business/src/Blockchain/Contracts/Native/ConsensusContract.cs
Phantasma.Business/src/Blockchain/Contracts/Native/DexContract.cs
Phantasma.Business/src/Blockchain/Contracts/Native/ExchangeContract.cs
Phantasma.Business/src/Blockchain/Contracts/Native/GasContract.cs
Phantasma.Business/src/Blockchain/Nexus/NexusTokens.cs
Phantasma.Business/src/Blockchain/VM/ExtCalls.cs
Phantasma.Business/src/Phantasma.Business.csproj
Phantasma.Business/tests/Blockchain/Contracts/GasContractTests.cs
Phantasma.Business/tests/Blockchain/ExtCallsTests.cs
Phantasma.Core/src/Domain/DomainSettings.cs
Phantasma.Core/src/Phantasma.Core.csproj
Phantasma.Infrastructure/src/Phantasma.Infrastructure.csproj

Update Version 17 

---

Phantasma.Business/src/Blockchain/Contracts/Native/StakeContract.cs
Phantasma.Core/src/Domain/Contract/Stake/StakeExceptions.cs

[113] Bug fixing Stake Contract / Unstake

---

Phantasma.Business/src/Blockchain/VM/EVMContext.cs
Phantasma.Business/src/Blockchain/VM/ExtCalls.cs
Phantasma.Business/tests/Blockchain/ExtCallsTests.cs

- Added Tests to The Validate Address and to the Get Nexus
- Added Special Calls
- Added new method to convert the address without checking contracts.

Added new ExtCalls for Get Nexus and Validate an Address.

---

Phantasma.Infrastructure/src/API/Controllers/RpcController.cs

- Fix's to RPC controller to work with new extended default values.
- Fix to sending the Context to the Call.

Fix's to RPC Controller

---

Phantasma.Business/src/Blockchain/Chains/Chain.cs
Phantasma.Business/src/Blockchain/Contracts/Native/StakeContract.cs
Phantasma.Business/tests/Blockchain/ChainTests.cs
Phantasma.Business/tests/Blockchain/Contracts/GasContractTests.cs
Phantasma.Business/tests/Blockchain/Contracts/Legacy/AccountContracTestLegacy.cs
Phantasma.Business/tests/Blockchain/Contracts/Legacy/StakeContractTestLegacy.cs
Phantasma.Business/tests/Blockchain/Exploits/Exploits.cs
Phantasma.Business/tests/Blockchain/NexusTestsSimulator.cs
Phantasma.Business/tests/Simulator/NexusSimulator.cs
Phantasma.Core/src/Domain/DomainSettings.cs
Phantasma.Node/src/ABCIConnector.cs
testnet-debug-arm64.sh
testnet-debug.sh
testnet-startup-arm64.sh
testnet-startup.sh

- Fixing startup scripts for testing / debuging.
- Fix Auto inflation transaction.

[118] Fix the auto inflation transaction.

---

Phantasma.Business/src/CodeGen/Assembler/Instruction.cs
Phantasma.Business/src/VM/Disassembler.cs
Phantasma.Business/src/VM/ScriptContext.cs
Phantasma.Business/src/VM/Structs/Instruction.cs
Phantasma.Business/tests/Blockchain/GasMachineTests.cs
Phantasma.Business/tests/VM/InstructionTest.cs
Phantasma.Business/tests/VM/ScriptContextConstants.cs
Phantasma.Business/tests/VM/ScriptContextTest.cs
Phantasma.Core/src/Domain/VM/Enums/Opcodes.cs
Phantasma.Core/src/Domain/VM/VMObject.cs

Add Remove Instructions set to the chain.

---

Phantasma.Business/src/Blockchain/Contracts/Native/ConsensusContract.cs
Phantasma.Business/src/Blockchain/Contracts/Native/RankingContract.cs
Phantasma.Core/src/Domain/Contract/LeaderboardDetails/Structs/Leaderboard.cs
Phantasma.Core/src/Domain/Contract/LeaderboardDetails/Structs/LeaderboardRow.cs
Phantasma.Infrastructure/src/API/APIChainService.cs

This PR is made to improve the Voting System and path the leaderboard system.

Improving Leaderboard and Voting System.

---

Phantasma.Infrastructure/src/API/Controllers/TransactionController.cs

Mitigate progress.

---

Phantasma.Business/src/Blockchain/VM/Runtime/RuntimeContext.cs

Allow Invoke
